---
title: 'Class 9 - Controlling for Confounding'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Readings
#### Required
- **[Morgan and Winship, Counterfactuals and Causal Inference, Chapters 3 and 5](Classes/Class_9/Readings/M&W.pdf)**
- **[Rubin, Donald, "For Objective Causal Inference, Design Trumps Analysis"](Classes/Class_9/Readings/Rubin Design Trumps Analysis.pdf)**
- **[Angrist & Pischke, Mastering 'Metrics, Ch. 2](Classes/Class_9/Readings/A&P_Ch.2.pdf)**
- **[Paper: Baldwin, Kate, 2013, "Why Vote with the Chief? Political Connections and Public Goods Provision in Zambia", American Journal of Political Science, 57:4](Classes/Class_9/Replication/Baldwin 2013.pdf)**

#### Additional Readings
- [Imbens and Rubin, Ch. 12](Classes/Class_9/Readings/Imbens and Rubin Ch.12.pdf)

<br> </br>

## [Lecture Slides](Classes/Class_9/Slides_Controls_v2.pdf)

## [Lab Exercise to Complete during Class](Classes/Class_9/Lab Exercise/Exercise_Controls_v6.pdf)
  - [Suggested Responses](Classes/Class_9/Lab Exercise/Exercise_Controls_v6_Suggested_Responses_Suggested_Responses.pdf)

## Replication Exercise
 - [Exercise](Classes/Class_9/Replication/Replication_Controls_v5.pdf) 
 - [Paper: Baldwin, Kate, 2013, "Why Vote with the Chief? Political Connections and Public Goods Provision in Zambia", American Journal of Political Science, 57:4](Classes/Class_9/Replication/Baldwin 2013.pdf) 
 - [Data](Classes/Class_9/Replication/Baldwin_adjusted.csv) 
 - [Suggested Responses](Classes/Class_9/Replication/Replication_Controls_v5_Suggested_Responses.pdf)

