---
title: 'Class 4 - Lab and Survey Experiments'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Readings
#### Required
- **[Hainmueller, Jens, Daniel J Hopkins and Teppei Yamamoto, 2013, Causal Inference in Conjoint Analysis: Understanding Multidimensional Choices via Stated Preference Experiments, Political Analysis, pp.1-30](Classes/Class_4/Readings/Jens et al 2013 Conjoint.pdf)**
- **[Gaines, Brain J., James Kuklinski and Paul J. Quirk, 2007, The Logic of the Survey Experiment Reexamined, Political Analysis 15:1](Classes/Class_4/Readings/Gaines et al 2006.pdf)**
- **[Levitt, Steven D. and John A List, 2006, What do Laboratory Experiments Tell us about the Real World?](Classes/Class_4/Readings/Levitt and List 2006.pdf)**


#### Additional Readings
- [Blair, Graeme and Kosuke Imai, 2012, Statistical Analysis of List Experiments, Political Analysis, 20:47-77](Classes/Class_4/Readings/Blair List.pdf)
- [Hainmueller, Jens, Dominik Hangartner and Teppei Yamamoto, 2014, Validating vignette and conjoint survey experiments against real-world behavior, PNAS, pp.1-6](Classes/Class_4/Readings/Hainmueller 2014.pdf)
- [Bueno, Natalia S. Bueno and Thad Dunning, 2017, Race, Resources, and Representation: Evidence from Brazilian Politicians, World Politics, 69:2](Classes/Class_4/Readings/Bueno and Dunning 2017.pdf)
- **[Habyarimana, James, Macartan Humphreys, Daniel N Posner, Jeremy M. Weinstein, 2007, Why Does Ethnicity Diversity Undermine Public Goods Provision? American Political Science Review, 101:4](Classes/Class_4/Readings/Habyarimana et al 2007.pdf)**
- [Hoff, Karla and Priyanka Pandey, 2004, Belief Systems and Durable Inequalities, World Bank Policy Research Working Paper 3351](Classes/Class_4/Readings/Hoff and Pandey 2004.pdf)

<br> </br>

## [Lecture Slides](Classes/Class_4/Slides_v1.pdf)

## Replication Exercise
- [Exercise](Classes/Class_4/Replication/)
- [Paper:Whitt, Sam, 2014, Social Norms in the Aftermath of Ethnic Violence: Ethnicity and Fairness in Non-Costly Decision Making, Journal of Conflict Resolution, 58:1](Classes/Class_4/Readings/Whitt 2014.pdf)
    - [Supplementary Appendix to Paper](Classes/Class_4/Replication/Supplementary_Appendix_final.pdf)
- [Data](Classes/Class_4/Replication/replication.dta)
