---
title: 'Class 3 - Field Experiments'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Readings
#### Required
- **[Joshua D Angrist and Steve Pischke. Mastering 'Metrics. 2015. pp. 26 - 46](Classes/Class_3/Readings/Angrist_Pischke_26_46.pdf)**
- **[Alan S. Gerber and Donald P Green. Field Experiments: Design, Analysis and Interpretation. W.W. Norton & Company, 2012. Chs. 1-2.](Classes/Class_3/Readings/Gerber_Green_Ch1_2.pdf)**
- **[Esther Duflo, Rachel Glennerster and Michael Kremer (2007), Using Randomization in Development Economics Research : A Toolkit, CEPR Discussion Paper 6059, Sections 1, 2.1, 2.2, 3, 5, 7, 8.](Classes/Class_3/Readings/Duflo_Randomization_Toolkit.pdf)**

#### Additional Readings
- [Guido W. Imbens and Donald B Rubin. Causal Inference for Statistics, Social, and Biomedical Sciences. 2015. Ch. 6](Classes/Class_3/Readings/Imbens_Rubin_104_125.pdf)
- [Benjamin A. Olken. Direct Democracy and Local Public Goods: Evidence from a Field Experiment in Indonesia. American Political Science Review, 104(02):243-267, May 2010.](http://economics.mit.edu/files/5224)

<br> </br>

## [Lecture Slides](Classes/Class_3/Slides_Class3_v5.pdf)

## [Experiments App](https://poliong.shinyapps.io/to_deploy/)

## [Lab Exercise to Complete during Class](Classes/Class_3/Exercise_Field_Exp_v1.pdf)

## Replication Exercise
- [Paper: Alan S. Gerber, et al. Social Pressure and Voter Turnout: Evidence from a Large-Scale Field Experiment. American Political Science Review, 102(1), February 2008.](Classes/Class_3/Replication/Gerber Green and Larimer 2008.pdf)
- [Exercise](Classes/Class_3/Replication/Replication_Exercise_1_v5.pdf)
- [Data](Classes/Class_3/Replication/GGL_data_prepared.csv)
