---
title: 'Research Project'
output: html_document
---

<style>
.column-left{
  float: left;
  width: 50%;
  text-align: left;
}
.column-right{
  float: right;
  width: 50%;
  text-align: right;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<div class="column-left">
The research project is designed to give you an opportunity to practice implementing at least one of the methodologies studied in this course to answer your own research question. The paper should be no more than 15 pages and can be in English or Portuguese.

Your paper and *all* of your data processing and analysis code should be submitted by email by in July 2021. Your analysis should be reproducible.

Suggestions:  
    - Pick a simple, clear and interesting research question  
    - Make sure you have the right data available to apply your methodology  
    - Don't worry about the substantive results, focus on a valid and thorough implementation of the research methodology and interpreting the results
</div>


